version: '3.11.4'
services:
  python:
    command: python3 main.py
    image: mariast123835/dash-demo-2:a2.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
  mlflow:
    command: mlflow server -h 0.0.0.0 --workers=8 --gunicorn-opts "--timeout 300"
    image: mlflow:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000